// site/src/components/Segmented.tsx
import { useRef } from 'react'
import { useHighlightIndicator } from '@guillemservera/react-details/highlight-indicator'
import { useProximityHover } from '@guillemservera/react-details/proximity-hover'

interface Props<T extends string | number> {
  value: T
  options: readonly { value: T, label: string, disabled?: boolean }[]
  onChange: (value: T) => void
}

export default function Segmented<T extends string | number>({ value, options, onChange }: Props<T>) {
  // Dogfooding: the selected pill glides with the value; hover only tints the nearest segment's text.
  const root = useRef<HTMLDivElement>(null)
  const selected = useRef<HTMLDivElement>(null)
  useProximityHover(root, { axis: 'xy' }) // segments wrap onto a second row on narrow screens
  useHighlightIndicator(root, selected, { target: '[aria-pressed="true"]', motion: 'moderate' })

  return (
    <div ref={root} className="segmented">
      <div ref={selected} aria-hidden="true" className="segmented-selected" />
      {options.map(option => (
        <button
          key={option.value}
          type="button"
          data-highlight-item=""
          aria-pressed={value === option.value}
          disabled={option.disabled}
          onClick={() => onChange(option.value)}
        >
          {option.label}
        </button>
      ))}
    </div>
  )
}

// site/src/components/Segmented.vue
<script setup lang="ts" generic="T extends string | number">
import { useTemplateRef } from 'vue'
import { useHighlightIndicator, useProximityHover } from '@guillemservera/vue-details'

defineProps<{ options: readonly { value: T, label: string, disabled?: boolean }[] }>()
const model = defineModel<T>({ required: true })

// Dogfooding: the selected pill glides with v-model; hover only tints the nearest segment's text.
const root = useTemplateRef<HTMLElement>('root')
useProximityHover(root, { axis: 'xy' }) // segments wrap onto a second row on narrow screens
useHighlightIndicator(root, useTemplateRef('selected'), { target: '[aria-pressed="true"]', motion: 'moderate' })
</script>

<template>
  <div ref="root" class="segmented">
    <div ref="selected" aria-hidden="true" class="segmented-selected" />
    <button
      v-for="option in options"
      :key="option.value"
      type="button"
      data-highlight-item
      :aria-pressed="model === option.value"
      :disabled="option.disabled"
      @click="model = option.value"
    >
      {{ option.label }}
    </button>
  </div>
</template>
