// site/src/demos/react/Playground.tsx
import { useState, type CSSProperties } from 'react'
import DemoList from './DemoList'
import Segmented from '../../components/Segmented'
import { axes, copy, counts, initialState, PLAIN_MAX, playgroundSnippet, renderers, type PlaygroundMode, type PlaygroundState } from '../playground'

export default function Playground({ mode }: { mode: PlaygroundMode }) {
  const [s, setState] = useState(initialState)
  const set = (patch: Partial<PlaygroundState>) => setState(prev => {
    const next = { ...prev, ...patch }
    if (next.count > PLAIN_MAX) next.renderer = 'virtual'
    return next
  })

  return (
    <>
      <header>
        <h1>{copy[mode].title}</h1>
        <p>{copy[mode].text}</p>
      </header>

      <section className="card">
        {mode === 'compare'
          ? (
              <div className={`compare ${s.axis}`}>
                <figure>
                  <figcaption>:hover</figcaption>
                  <DemoList key={`native-${s.axis}`} {...s} mode="native" keyboard={false} bare />
                </figure>
                <figure>
                  <figcaption>useProximityHover</figcaption>
                  <DemoList key={`proximity-${s.axis}`} {...s} mode="proximity" keyboard={false} bare />
                </figure>
              </div>
            )
          : <DemoList key={`${mode}-${s.axis}-${s.keyboard}`} {...s} mode={mode} />}

        <div className="controls">
          <div className="control">
            <span className="label">axis</span>
            <Segmented value={s.axis} options={axes} onChange={axis => set({ axis })} />
          </div>
          <div className="control">
            <span className="label">renderer</span>
            <Segmented value={s.renderer} options={renderers(s.count)} onChange={renderer => set({ renderer })} />
          </div>
          <div className="control">
            <span className="label">items</span>
            <Segmented value={s.count} options={counts} onChange={count => set({ count })} />
          </div>
          {mode !== 'compare' && (
            <>
              {mode === 'proximity' && (
                <>
                  <label className="control">
                    <span className="label">keyboard</span>
                    <input checked={s.keyboard} onChange={e => set({ keyboard: e.target.checked })} className="switch" type="checkbox" />
                  </label>
                  <label className="control">
                    <span className="label">reducedMotion</span>
                    <input checked={s.reducedMotion} onChange={e => set({ reducedMotion: e.target.checked })} className="switch" type="checkbox" />
                  </label>
                </>
              )}
              <label className="control">
                <span className="label">resumeDistance</span>
                <span className="slider">
                  <input
                    value={s.resumeDistance}
                    onChange={e => set({ resumeDistance: +e.target.value })}
                    style={{ '--p': s.resumeDistance / 40 } as CSSProperties}
                    type="range"
                    min="0"
                    max="40"
                    step="1"
                  />
                  <output>{s.resumeDistance}px</output>
                </span>
              </label>
              {(mode === 'keyboard' || s.keyboard) && (
                <>
                  <label className="control">
                    <span className="label">loop</span>
                    <input checked={s.loop} onChange={e => set({ loop: e.target.checked })} className="switch" type="checkbox" />
                  </label>
                  <label className="control">
                    <span className="label">whileHovered</span>
                    <input checked={s.whileHovered} onChange={e => set({ whileHovered: e.target.checked })} className="switch" type="checkbox" />
                  </label>
                </>
              )}
            </>
          )}
        </div>

        <div className="code">
          <pre>{playgroundSnippet(mode, s)}</pre>
        </div>
      </section>
    </>
  )
}

// site/src/demos/vue/Playground.vue
<script setup lang="ts">
import { computed, reactive, watch } from 'vue'
import DemoList from './DemoList.vue'
import Segmented from '../../components/Segmented.vue'
import { axes, copy, counts, initialState, PLAIN_MAX, playgroundSnippet, renderers, type PlaygroundMode } from '../playground'

const props = defineProps<{ mode: PlaygroundMode }>()

const s = reactive({ ...initialState })
watch(() => s.count, (v) => {
  if (v > PLAIN_MAX) s.renderer = 'virtual'
})

const snippet = computed(() => playgroundSnippet(props.mode, s))
</script>

<template>
  <header>
    <h1>{{ copy[mode].title }}</h1>
    <p>{{ copy[mode].text }}</p>
  </header>

  <section class="card">
    <div v-if="mode === 'compare'" class="compare" :class="s.axis">
      <figure>
        <figcaption>:hover</figcaption>
        <DemoList :key="`native-${s.axis}`" v-bind="s" mode="native" :keyboard="false" bare />
      </figure>
      <figure>
        <figcaption>useProximityHover</figcaption>
        <DemoList :key="`proximity-${s.axis}`" v-bind="s" mode="proximity" :keyboard="false" bare />
      </figure>
    </div>
    <DemoList v-else :key="`${mode}-${s.axis}-${s.keyboard}`" :mode="mode" v-bind="s" />

    <div class="controls">
      <div class="control">
        <span class="label">axis</span>
        <Segmented v-model="s.axis" :options="axes" />
      </div>
      <div class="control">
        <span class="label">renderer</span>
        <Segmented v-model="s.renderer" :options="renderers(s.count)" />
      </div>
      <div class="control">
        <span class="label">items</span>
        <Segmented v-model="s.count" :options="counts" />
      </div>
      <template v-if="mode !== 'compare'">
        <template v-if="mode === 'proximity'">
          <label class="control">
            <span class="label">keyboard</span>
            <input v-model="s.keyboard" class="switch" type="checkbox">
          </label>
          <label class="control">
            <span class="label">reducedMotion</span>
            <input v-model="s.reducedMotion" class="switch" type="checkbox">
          </label>
        </template>
        <label class="control">
          <span class="label">resumeDistance</span>
          <span class="slider">
            <input v-model.number="s.resumeDistance" :style="{ '--p': s.resumeDistance / 40 }" type="range" min="0" max="40" step="1">
            <output>{{ s.resumeDistance }}px</output>
          </span>
        </label>
        <template v-if="mode === 'keyboard' || s.keyboard">
          <label class="control">
            <span class="label">loop</span>
            <input v-model="s.loop" class="switch" type="checkbox">
          </label>
          <label class="control">
            <span class="label">whileHovered</span>
            <input v-model="s.whileHovered" class="switch" type="checkbox">
          </label>
        </template>
      </template>
    </div>

    <div class="code">
      <pre>{{ snippet }}</pre>
    </div>
  </section>
</template>
