// site/src/demos/react/RollingTextDemo.tsx
import { useRef, useState, type CSSProperties } from 'react'
import { useRollingText } from '@guillemservera/react-details'
import Segmented from '../../components/Segmented'
import { textExamples as examples } from '../playground'
import { useTimer } from './useTimer'

const directions = [{ value: 'up', label: 'up' }, { value: 'down', label: 'down' }] as const

export default function RollingTextDemo() {
  const [text, setText] = useState('Make every word count.')
  const [duration, setDuration] = useState(600)
  const [direction, setDirection] = useState<'up' | 'down'>('up')
  const [animated, setAnimated] = useState(true)
  const source = useRef<HTMLSpanElement>(null)
  const viewport = useRef<HTMLSpanElement>(null)
  useRollingText(source, viewport, { duration, direction, animated })

  const timer = useTimer()
  const select = (value: string) => {
    timer.clear()
    setText(value)
  }
  const burst = () => {
    const original = text
    select('A new perspective.')
    timer.set(() => {
      setText('Then something different.')
      timer.set(() => setText(original), 120)
    }, 120)
  }

  const snippet = `import { useRef, useState } from 'react'
import { useRollingText } from '@guillemservera/react-details/rolling-text'

const [text, setText] = useState(${JSON.stringify(text)})
const source = useRef<HTMLSpanElement>(null)
const viewport = useRef<HTMLSpanElement>(null)
useRollingText(source, viewport, { duration: ${duration}, direction: ${JSON.stringify(direction)}, animated: ${animated} })

// JSX — put typography on the common parent:
<span style={{ position: 'relative', display: 'inline-block', whiteSpace: 'pre' }}>
  <span ref={source} style={{ display: 'inline-block', minHeight: '1lh' }}>{text}</span>
  <span ref={viewport} aria-hidden="true" />
</span>`

  return (
    <>
      <header>
        <h1>useRollingText</h1>
        <p>Complete words or phrases slide together as one row. Interrupt or return to a phrase and it continues from where it is.</p>
      </header>

      <section className="card">
        <div className="text-stage">
          <span className="text-frame">
            <span ref={source} style={{ display: 'inline-block', minHeight: '1lh' }}>{text}</span>
            <span ref={viewport} aria-hidden="true"></span>
          </span>
        </div>

        <div className="controls">
          <label className="control">
            <span className="label">Text</span>
            <input value={text} onChange={e => select(e.target.value)} className="text-input" type="text" />
          </label>
          <div className="text-actions">
            {examples.map(example => <button key={example} type="button" onClick={() => select(example)}>{example}</button>)}
            <button type="button" onClick={() => select('')}>Empty</button>
            <button type="button" onClick={burst}>Burst &amp; return</button>
          </div>
          <label className="control">
            <span className="label">Duration</span>
            <span className="slider">
              <input value={duration} onChange={e => setDuration(+e.target.value)} style={{ '--p': duration / 2000 } as CSSProperties} type="range" min="0" max="2000" step="50" />
              <output>{duration}ms</output>
            </span>
          </label>
          <div className="control">
            <span className="label">Direction</span>
            <Segmented value={direction} options={directions} onChange={setDirection} />
          </div>
          <label className="control">
            <span className="label">Animated</span>
            <input checked={animated} onChange={e => setAnimated(e.target.checked)} className="switch" type="checkbox" />
          </label>
        </div>

        <div className="code"><pre>{snippet}</pre></div>
      </section>
    </>
  )
}

// site/src/demos/vue/RollingTextDemo.vue
<script setup lang="ts">
import { computed, onScopeDispose, ref, useTemplateRef } from 'vue'
import { textExamples as examples } from '../playground'
import { useRollingText } from '@guillemservera/vue-details'
import Segmented from '../../components/Segmented.vue'

const text = ref('Make every word count.')
const duration = ref(600)
const direction = ref<'up' | 'down'>('up')
const animated = ref(true)
const source = useTemplateRef<HTMLElement>('source')
const viewport = useTemplateRef<HTMLElement>('viewport')
useRollingText(source, viewport, { duration, direction, animated })

const directions = [{ value: 'up', label: 'up' }, { value: 'down', label: 'down' }] as const
let timer: number | undefined
function stopBurst() {
  clearTimeout(timer)
}
function select(value: string) {
  stopBurst()
  text.value = value
}
function burst() {
  stopBurst()
  const original = text.value
  text.value = 'A new perspective.'
  timer = window.setTimeout(() => {
    text.value = 'Then something different.'
    timer = window.setTimeout(() => { text.value = original }, 120)
  }, 120)
}
onScopeDispose(stopBurst)

const snippet = computed(() => `import { ref, useTemplateRef } from 'vue'
import { useRollingText } from '@guillemservera/vue-details/rolling-text'

const text = ref(${JSON.stringify(text.value)})
const duration = ref(${duration.value})
const direction = ref(${JSON.stringify(direction.value)})
const animated = ref(${animated.value})
const source = useTemplateRef<HTMLElement>('source')
const viewport = useTemplateRef<HTMLElement>('viewport')
useRollingText(source, viewport, { duration, direction, animated })

// Template — put typography on the common parent:
<span style="position: relative; display: inline-block; white-space: pre">
  <span ref="source" style="display: inline-block; min-height: 1lh">{{ text }}</span>
  <span ref="viewport" aria-hidden="true"></span>
</span>`)
</script>

<template>
  <header>
    <h1>useRollingText</h1>
    <p>Complete words or phrases slide together as one row. Interrupt or return to a phrase and it continues from where it is.</p>
  </header>

  <section class="card">
    <div class="text-stage">
      <span class="text-frame">
        <span ref="source" style="display: inline-block; min-height: 1lh">{{ text }}</span>
        <span ref="viewport" aria-hidden="true"></span>
      </span>
    </div>

    <div class="controls">
      <label class="control">
        <span class="label">Text</span>
        <input v-model="text" class="text-input" type="text" @input="stopBurst">
      </label>
      <div class="text-actions">
        <button v-for="example in examples" :key="example" type="button" @click="select(example)">{{ example }}</button>
        <button type="button" @click="select('')">Empty</button>
        <button type="button" @click="burst">Burst &amp; return</button>
      </div>
      <label class="control">
        <span class="label">Duration</span>
        <span class="slider">
          <input v-model.number="duration" :style="{ '--p': duration / 2000 }" type="range" min="0" max="2000" step="50">
          <output>{{ duration }}ms</output>
        </span>
      </label>
      <div class="control">
        <span class="label">Direction</span>
        <Segmented v-model="direction" :options="directions" />
      </div>
      <label class="control">
        <span class="label">Animated</span>
        <input v-model="animated" class="switch" type="checkbox">
      </label>
    </div>

    <div class="code"><pre>{{ snippet }}</pre></div>
  </section>
</template>
